### ISSUE TITLE
queryPurchaseHistoryAsync vs queryPurchases

### ISSUE THREAD

**Issue by davidkraus** [vanniktech/RxBilling#14]
Hey,

i'm having following problem:
Your code only calls `queryPurchaseHistoryAsync`
documentation says:
> Returns the most recent purchase made by the user for each SKU, even if that purchase is expired, canceled, or consumed.

and never `queryPurchases` which i think would be the "right" call because using the first one you can't tell what the state of that purchase is (cancelled, refunded ...).

Just for context: we try to implement subscriptions without a server (still don't know if this is a good idea - the internet is full of contradictory information. Google says it should work but is not "secure")

So calling `queryPurchaseHistoryAsync` might be ok if you can query your own server to check what is up with your purchase but i can't do that so i have to rely on the information google gives me.

Did you have any of those problems? How do you check the state of the purchase?

**Comment by vanniktech** [comment]
Huh, interesting. I have the same use case as you. I'm not verifying them with my server but I haven't had any problems so far.

**Comment by vanniktech** [comment]
There's some more information here 	https://issuetracker.google.com/issues/123449154 but seems like you're right and we should be calling `queryPurchases` but even then we won't get the state

**Comment by davidkraus** [comment]
yeah i saw that reference in your code. Play billing is somehow really confusing.

From what i understand `queryPurchases` should (at some point in time) give me the correct state: (nothing if no purchases/subscriptions are active or it should give me the purchases/subscriptions with all its info).

the thing about `queryPurchases` is that apparently it is powered by a cache that will only refresh after 24/48 hours (don't know exactly). And i don't know if this also applies for the test subscriptions. I need to change the call in your library and test it. The caching is fine for my use case but i think if your app needs to respond quickly to canceled subscriptions you need your own server (just a speculation from my side). If you want to get even more confused read 
 https://github.com/googlesamples/android-play-billing/issues/122 ;)

**Comment by vanniktech** [comment]
I'd prefer to make the change once `queryPurchases` behaves correctly. I've also tried test in app purchases and so far I haven't had any problems with `queryPurchaseHistoryAsync`,

**Comment by davidkraus** [comment]
ok thanks, i will change the code in my app and report back

**Comment by davidkraus** [comment]
So i did a few tests: for us `queryPurchases` works:
- it returns the active subscriptions of the user
- once the subscription is canceled/has ended it returns nothing

`queryPurchaseHistoryAsync` always returns a value (after the purchase of course) no matter if it is still valid or not.

**Comment by vanniktech** [comment]
So, we can close?

**Comment by davidkraus** [comment]
depends ;), we currently use a version of your lib where i switched to `queryPurchases` because we need to know what is happening with our subscription.

Best thing would be if we had the ability to use both calls with your lib.

**Comment by vanniktech** [comment]
Ah understand. Let me think about it

**Comment by vanniktech** [comment]
Haven't had a use case for this so I'll prefer to have less.
