### ISSUE TITLE
Unresolved reference: RxBilling

### ISSUE THREAD

**Issue by danilink88** [vanniktech/RxBilling#27]
Hello!

First thank you for uploading your library. I'm trying to implement billing with Rx and I think it will be very useful to me. It looks good, but I'm having trouble. When adding the last dependency in my .gradle (implementation 'com.vanniktech: rxbilling-google-play-library: 0.5.0'), despite synchronizing everything correctly, it seems that it does not recognize the library files. In particular I try to use RxBilling and it tells me that it does not exist. Do I have to do something else?

As an alternative, I tried to add version 4, despite being deprecated, and in this case it does recognize the files, but the problem is that when trying to recover current purchases it returns the following error: _Support for pending purchases must be enabled. Enable this by calling 'enablePendingPurchases ()' on BillingClientBuilder._ , but I don't know how to do it from RxBilling...

Thank you!

**Comment by vanniktech** [comment]
Not sure how I can help you without full reproduction steps.
